phraseapp:
  access_token: 95dbbf1d0bdf587582a64b635dc1738edfd4b7feb6a0f3633ff35fef5f462252
  project_id: 8e1da11a577bc4eb2ca0a2b4011d165d
  push:
    sources:
    - file: airmapsdk/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
  pull:
    targets:
    - file: airmapsdk/src/main/res/values-<locale_code>/translated-strings.xml
      params:
        file_format: xml
        format_options: { convert_placeholder: true }
