phraseapp:
  access_token: ba231de1c01e4dc42988940bf77ef1d39d76a11de27033a0656a72319cf69ef6
  project_id: 8e1da11a577bc4eb2ca0a2b4011d165d
  push:
    sources:
    - file: airmapsdk/src/main/res/values/androidstrings.xml #android only
      params:
        tags: "android"
        file_format: xml
        locale_id: en
  pull:
    targets:
    - file: airmapsdk/src/main/res/values-<locale_name>/translated-strings.xml
      params:
        tag: "ios"
        file_format: xml
        convert_emoji: true
        format_options: 
          convert_placeholder: true
          escape_linebreaks: true

    - file: airmapsdk/src/main/res/values-<locale_name>/androidstrings.xml #android only
      params:
        tag: "android"
        file_format: xml
        convert_emoji: true
        format_options:
          convert_placeholder: true
          escape_linebreaks: true
