phraseapp:
  access_token: 95dbbf1d0bdf587582a64b635dc1738edfd4b7feb6a0f3633ff35fef5f462252
  project_id: 1128fe24e26cfd941681baa24aadc4e4
  push:
    sources:
    - file: ../airmapsdk/src/main/res/values-<locale_code>/androidstrings.xml
      params:
        file_format: xml
        tags: "android"
  pull:
    targets:
    - file: ../airmapsdk/src/main/res/values-<locale_code>/androidstrings.xml
      params:
        file_format: xml
        convert_emoji: true
        format_options: 
          convert_placeholder: true
          escape_linebreaks: true
